version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    restart: always
    # As variáveis de ambiente serão configuradas na interface do EasyPanel

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    restart: always
    # As variáveis de ambiente serão configuradas na interface do EasyPanel

